version: "3.8"

services:
  nginx:
    build: ./nginx
    container_name: self_healing_nginx
    ports:
      - "8080:80"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - "9093:9093"

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:edge
    container_name: nginx_prometheus_exporter
    command:
      - --nginx.scrape-uri=http://nginx/stub_status
    ports:
      - "9113:9113"

  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    ports:
      - "9115:9115"

  webhook:
    build: ./webhook
    container_name: webhook
    ports:
      - "5001:5001"
    volumes:
      - ./ansible:/ansible   # so webhook can run your playbook
      - /var/run/docker.sock:/var/run/docker.sock   # allows webhook to restart NGINX container
    restart: always
