groups:
  - name: nginx-alerts
    rules:
      - alert: NginxDown
        expr: probe_success{job="blackbox"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Nginx is DOWN"
          description: "Nginx target {{ $labels.instance }} is not responding."

