name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r webhook/requirements.txt || true

      - name: Lint
        run: |
          pip install flake8 || true
          flake8 webhook || true

      - name: Run tests
        run: |
          pip install pytest || true
          pytest -q || true
